<?php

namespace Tests\Feature\Api;

use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class OrderControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Create test products
        Product::truncate();
        Product::query()->insert([
            [
                'name' => 'Washing Machine #1',
                'description' => 'test description washing machine',
                'price' => 450.50,
                'stock' => 23
            ],
            [
                'name' => 'Kettle #1',
                'description' => 'test description kettle',
                'price' => 25.00,
                'stock' => 10
            ],
            [
                'name' => 'Hammer #3',
                'description' => 'Hammer description',
                'price' => 75.25,
                'stock' => 5
            ]
        ]);
    }

    /**
     * A basic feature test example.
     */
    public function test_order_api(): void
    {
        // Make sure test products are created from the product database (mysql_product connection)
        $this->assertEquals(3, Product::count());
        // Test order product #1
        $hammer = Product::query()->where('name', 'Hammer #3')->first();
        $this->assertNotEmpty($hammer);
        $hammerOrder = new \stdClass();
        $hammerOrder->product_id = $hammer->id;
        $hammerOrder->product_name = $hammer->name;
        $hammerOrder->product_price = $hammer->price;
        $hammerOrder->product_description = $hammer->description;
        // Order 2 pcs
        $hammerOrder->quantity = 2;
        // Test order product #2
        $kettle = Product::query()->where('name', 'Kettle #1')->first();
        $this->assertNotEmpty($kettle);
        $kettleOrder = new \stdClass();
        $kettleOrder->product_id = $kettle->id;
        $kettleOrder->product_name = $kettle->name;
        $kettleOrder->product_description = $kettle->description;
        $kettleOrder->product_price = $kettle->price;
        // Order 5 pcs
        $kettleOrder->quantity = 5;

        $formBody = [
            'email' => 'johenelpl@gmail.com',
            'address' => 'test address',
            'note' => 'test note',
            'orders' => [
                $hammerOrder, $kettleOrder
            ]
        ];

        $response = $this->postJson('/api/orders', $formBody);
        $response->assertOk();

        $order = json_decode($response->getContent());

        /*
         *  Validate order data
         */

        // Validate total price - 2 hammer (150.50) + 5 Kettle (125.00) = 275.50
        $this->assertEquals(275.50, $order->total_price);
        // Validate total price with tax - 275.50 + (275.50 x 0.12) = 308.56
        $this->assertEquals(308.56, $order->total_price_with_tax);
        // Validate total items - 2 hammer + 5 kettle = total of 7 items
        $this->assertEquals(7, $order->item_total_count);
        // Validate total unique product count - 2 products (hammer and kettle)
        $this->assertEquals(2, $order->product_count);

        /*
         *  Validate stock after order is made
         */

        // Validate hammer stock - Starting stock = 5, order quantity = 2, expected stock = 3
        $hammer->refresh();
        $this->assertEquals(3, $hammer->stock);
        // Validate kettle stock - Starting stock = 10, order quantity = 5, expected stock = 5
        $kettle->refresh();
        $this->assertEquals(5, $kettle->stock);
    }
}
